### ISSUE TITLE
[README]`.appleScrollBehavior`: Buttons are disabled in position `.middle`

### ISSUE THREAD

**Issue by jagodki** [LucasMucGH/BottomSheet#18] opened 2021-07-14 19:28 UTC
Hi,

first of all, you did an amazing job with this project :)

I implemented the bottom sheet on top of a map view without customising the positions and placed a some buttons on the bottom sheet. My problem is, that the buttons are disabled, when the bottom sheet is not in position .top:

<img width="318" alt="Bildschirmfoto 2021-07-14 um 21 24 45" src="https://user-images.githubusercontent.com/23242936/125680924-074fbac3-bff9-4eb6-b4f0-a418763d38d4.png">

If the bottom sheet will be pulled up to the .top-position, the buttons will not be disabled anymore:
<img width="325" alt="Bildschirmfoto 2021-07-14 um 21 25 39" src="https://user-images.githubusercontent.com/23242936/125681003-8b49e52f-5df3-4d93-ae69-4c1b36d09528.png">

Is this a feature (that can be customised) it or is it a bug?

Best Regards,
Christoph

**Comment by LucasMucGH** [comment] 2021-07-14 22:06
Hello Christoph,

First of all thank you for your kind words. 

Now to your issue. The problem is caused because you are using the following option `.appleScrollBehavior`.
Internally it disables the ScrollView, to prevent it from scrolling except when it is at the `.top` position, to mimic Apples BottomSheet. But because of inheritance it looks like the Buttons also get disabled.

This is not the intended behavior and as soon as I have time I will fix this. But for now I suggest you to add `.enabled(true)` to all of your buttons (I hope this will fix this for now).

Greetings,
Lucas

**Comment by jagodki** [comment] 2021-07-15 20:19
Thank you for your timely response. I can confirm, that the problem is related to the option .appleScrollBehavior.

**Comment by LucasMucGH** [comment] 2021-07-16 07:01
Hello, so I tested it and I figured out, that `.disabled(false)` has no effect because it is overridden by the ScrollView property.

Now I have the following options: implement a completely custom implementation of `UIScrollView` or using the `Introspect` library.

Using the introspect library works fine, but I’m not sure if I want to add an dependency to another package.

Greetings Lucas

**Comment by jagodki** [comment] 2021-07-16 18:35
Adding dependencies to another library would not be the best architecture. On the other side, Introspect is a productive ready library. Maybe it could be implemented as a non mandatory feature, so that users of BottomSheet have also the choice to use Introspect and if they don't want, the .appleScrollBehaviour works in the same way as at the moment.

**Comment by LucasMucGH** [comment] 2021-07-16 18:42
Im currently trying to implement my own adoption for `UIScrollView`, because I could not only solve your but also a couple more issues or add features by implementing this.

**Comment by LucasMucGH** [comment] 2021-07-21 14:51
Please have a look at `#temp-fix-18`, as it fixes your issue. For now you can just use this branch instead, until I implement a better solution. I will keep this branch up to date and I will leave this issue open until I found a better fix.
But please keep in mind, that im really busy at the moment I don't have an ETA for the final fix.

I hope this works for you,
Lucas

**Comment by jagodki** [comment] 2021-07-24 21:03
Great work, it works like a charm. Thank you for you effort :)

**Comment by MarcoCadei** [comment] 2021-11-27 16:07
When trying to use `temp-fix-18` I get an error  
```
Couldn’t check out revision ‘5b66c3163049688117a3a3d1b7df92bf18c2578a’:
Downloading Assets/ArtistSongsView.gif (14 MB)
```
It seems related to git lfs. @LucasMucGH can you please check?

**Comment by LucasMucGH** [comment] 2021-12-28 15:25
In favour of #39 im closing this issue now. In the next days the `#temp-fix-18` branch will be deleted and a final solution will be in the main branch.

**Closed by LucasMucGH** 2021-12-28 15:25 UTC
Labels: bug, Thank You ❤️
