### ISSUE TITLE
Weird blinking when trying to pull bottom sheet

### ISSUE THREAD

**Issue by ValeriyJefimov** [LucasMucGH/BottomSheet#40] opened 2021-12-29 01:37 UTC
Hey, Lucas. Thanx for such an awesome lib)

Had an issue after latest update when trying to pull down content. Code sample attached

```
...
    .bottomSheet(
        bottomSheetPosition: $position),
        options: [
            .appleScrollBehavior,
            .swipeToDismiss,
            .noBottomPosition,
            .dragIndicatorColor(.surface),
            .background(AnyView(Color.clear))
        ]) {
            BottomView(...)
        }
...

```

Also video sample attached 
https://user-images.githubusercontent.com/19861161/147619151-88d482ef-e8de-48f9-97b2-5e52faf0b6fc.mov

Thanx a lot)

**Comment by LucasMucGH** [comment] 2021-12-29 02:17
Thank you for your repot. Was this issue already present in the last version? I don’t think so, but I just want to be sure. I have an idea, what the problem could be and I will look deeper into it tomorrow.

**Comment by ValeriyJefimov** [comment] 2021-12-29 08:34
Thanx for your reply.
That issue was faced in 2.5.0)

**Comment by LucasMucGH** [comment] 2022-01-05 22:32
Hello, could you please confirm that the `#test` branch fixes your issue. After a lot of testing I can not reproduce it anymore with the test branch.

**Comment by ValeriyJefimov** [comment] 2022-01-08 15:40
@LucasMucGH  unfortunately cannot confirm. Try to pull down with low acceleration.

Sample code 

```
 Rectangle()
                        .foregroundColor(.red)
                        .bottomSheet(
                    bottomSheetPosition: $position,
                    options: [
                        .appleScrollBehavior,
                        .noBottomPosition,
                    ]) {
                        Rectangle()
                            .foregroundColor(.blue)
                            .frame(height: 300)
                            .padding([.trailing, .leading], 20)
                    }
```

**Comment by LucasMucGH** [comment] 2022-01-08 15:41
As no answer is provided, I will now merge the fix. If the bug isn't fixed, don't hesitate to re-open this issue.

**Comment by LucasMucGH** [comment] 2022-01-08 16:01
I tested your sample code. This are the results of my real device:


https://user-images.githubusercontent.com/63545066/148651063-5b77232f-4c78-4361-999b-c787642afcef.mov



There is indeed a small view glitch, but it only appears once when pulling the BottomSheet really slow down.
But because I don't know any other possibility for to implement this feature and it is now way better than before, I will see this issue as solved. The only other possibility is to remove this feature altogether, because it can't be implemented perfectly due to the problems with DragGesture on ScrollViews. Maybe I will find a workaround or something in the future.

I hope we can agree, that the issue can be seen as fixed now.

**Closed** 2022-01-08 19:33 UTC
Labels: bug, Thank You ❤️
